### ISSUE TITLE
compiler errors following readme build advice

### ISSUE THREAD

**Issue by bmillare** [Toccata-Lang/toccata#1]
Version info
`$ clang --version
clang version 4.0.1 (tags/RELEASE_401/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin`

For commit e337ed66868dbb369c6c95782196b701bf2583d1

`$ clang -O3 -g -fno-objc-arc -std=c99 -c core.c`

Succeeds

`$ clang -O3 -g -fno-objc-arc -o toccata -std=c99 core.o toccata.c -lpthread
core:1985:20: error: use of undeclared identifier 'PATH_MAX'
  char actualpath [PATH_MAX+1];
                   ^
core:1988:7: warning: implicit declaration of function 'realpath' is invalid in
      C99 [-Wimplicit-function-declaration]
  if (realpath(arg0Str->buffer, actualpath) == NULL) {
      ^
/Users/jim/toccata/dependencies/git/https://github.com/Toccata-Lang/Free.git/2ab53a3/free.toc:31:58: error: 
      use of undeclared identifier 'S_IEXEC'
Value *S_IEXEC_2036 = (Value *)&(Integer){IntegerType,-1,S_IEXEC}; 
                                                         ^
/Users/jim/toccata/dependencies/git/https://github.com/Toccata-Lang/ast.git/22fc8c6/ast.toc:85:3: warning: 
      implicit declaration of function 'strerror_r' is invalid in C99
      [-Wimplicit-function-declaration]
  strerror_r(errno, errStr, 1000);
  ^
/Users/jim/toccata/dependencies/git/https://github.com/Toccata-Lang/system.git/bed3aa7/system.toc:261:34: warning: 
      null passed to a callee that requires a non-null argument [-Wnonnull]
    execl(path->buffer, (char *)0);
                        ~~~~~~~~~^
3 warnings and 2 errors generated.`

Setting:
`export TOCCATA_DIR=/home/bmillare/dj/usr/src/toccata`

And then running again, same problem:
`clang -O3 -g -fno-objc-arc -o toccata -std=c99 core.o toccata.c -lpthread
core:1985:20: error: use of undeclared identifier 'PATH_MAX'
  char actualpath [PATH_MAX+1];
                   ^
core:1988:7: warning: implicit declaration of function 'realpath' is invalid in
      C99 [-Wimplicit-function-declaration]
  if (realpath(arg0Str->buffer, actualpath) == NULL) {
      ^
/Users/jim/toccata/dependencies/git/https://github.com/Toccata-Lang/Free.git/2ab53a3/free.toc:31:58: error: 
      use of undeclared identifier 'S_IEXEC'
Value *S_IEXEC_2036 = (Value *)&(Integer){IntegerType,-1,S_IEXEC}; 
                                                         ^
/Users/jim/toccata/dependencies/git/https://github.com/Toccata-Lang/ast.git/22fc8c6/ast.toc:85:3: warning: 
      implicit declaration of function 'strerror_r' is invalid in C99
      [-Wimplicit-function-declaration]
  strerror_r(errno, errStr, 1000);
  ^
/Users/jim/toccata/dependencies/git/https://github.com/Toccata-Lang/system.git/bed3aa7/system.toc:261:34: warning: 
      null passed to a callee that requires a non-null argument [-Wnonnull]
    execl(path->buffer, (char *)0);
                        ~~~~~~~~~^
3 warnings and 2 errors generated.`

**Comment by mtnygard** [comment]
Same issue here. Running clang-4.0.0

**Comment by jduey** [comment]
Thanks! I'll make this a priority as soon as I can. May be a couple of days, though.

**Comment by mtnygard** [comment]
@jduey What version of clang are you using? (I'm assuming that's the disconnect.)

**Comment by jduey** [comment]
Jims-MBP:examples jim$ clang --version
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix

It's the clang that comes standard with macOS 10.12.6 (Sierra)

**Comment by mtnygard** [comment]
OK, it's not the clang version. It's that the generated C code includes references to Darwin-specific headers and constants. S_IEXEC is defined in `sys/_types/_s_ifmt.h`, which is found buried way inside the macOS SDK inside the Xcode.app contents.

**Comment by mtnygard** [comment]
Also, Apple's habit of renumbering clang/llvm versions is really irritating. I'm looking at https://opensource.apple.com/source/clang/. It doesn't have version 900 in there yet, but version 800.0.42.1 corresponds to LLVM version 3.9.0.

**Comment by jduey** [comment]
Yes, very irritating.

**Comment by jduey** [comment]
Fixed this issue. Thanks for the report and mtnygard for the Docker container. Huge benefit.

**Comment by bmillare** [comment]
Looks fixed for me too. Thanks

**Comment by jduey** [comment]
Great to hear that.
