### ISSUE TITLE
compiled file size & runtime memory use

### ISSUE THREAD

**Issue by pekeler** [Toccata-Lang/toccata#3]
The Hello World example compiles to 360KB and requires 1.1MB ram to run on my Mac (without debug info and `-O1`). By comparison, the plain C Hello World is 8.2KB and 0.8MB.

Not bad compared to requiring a JVM. But how much could the toccata compiler optimize this to be closer to the plain C version?

I'm not suggesting to work on this now as I'm sure there are higher priorities. I'm just wondering about the long term suitability for embedded development and/or writing unix command line tools.

**Comment by jduey** [comment]
So you actually got it to compile and run. Winning! :)
I also assume you compiled without debug symbols.
There's quite a lot of code for the runtime linked in. Everything in core.c. But the biggest culprit is the fact that all of core.toc gets compile in as well. Doing some tree shaking would cut out a lot of that.
There's also a bunch of strings in there for when things break. These could be stripped or not put in. Actually, I think I'll have the option of those being stripped out in the C compiler. Thanks for the idea. :)
And there are probably other things. I'd definitely like to see Toccata used for embedded stuff.
