### ISSUE TITLE
How to compile core.toc?

### ISSUE THREAD

**Issue by pekeler** [Toccata-Lang/toccata#4]
`toccata core.toc > core.c` aborts with `'main' function is missing`. Is there some parameter for toccata I'd need to use?

**Comment by jduey** [comment]
Very poor naming on my part. 'core.c' should be named something like 'runtime.c' and 'core.toc' should be named 'stdlib.toc'.

You don't need (and can't) compile core.toc. It gets compiled automatically every time you compile a toccata file.

**Comment by pekeler** [comment]
Ah, thanks!
