### ISSUE TITLE
Latest version doesn't compile

### ISSUE THREAD

**Issue by PMunch** [Toccata-Lang/toccata#5]
When compiling toccata.c it complains that new-core.h is missing. Changing this to core.h and changing line 310091 to use core.h instead of new-core.h as well makes it compile and behave properly. Not sure if new-core.h has some other functionality that core.h doesn't have, so I created this as an issue and not as a PR.

**Comment by jduey** [comment]
Nope. I'm doing some work and needed to push some intermediate work to back it up off my machine. I'll fix ASAP.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by jduey** [comment]
Finally got everything lined out. Made some fundamental changes to the runtime that massively reduces memory usage. Look for a blog post soon.
