### ISSUE TITLE
FFI or External library support?

### ISSUE THREAD

**Issue by metacritical** [Toccata-Lang/toccata#9]
If one were to call functions from an external library say libsdl or something how could one do that in toccata?

**Comment by jduey** [comment]
You use the 'inline' expression which allows you to drop C code into a Toccata file. You can see examples in https://github.com/Toccata-Lang/system/blob/master/system.toc. There are quite a few things to get right mapping from Toccata parameters to C variable names. And it has to be integrated into Toccata's ref counting memory system. That's described here and a couple of following posts. http://www.toccata.io/2019/02/RefCounting.html

**Comment by metacritical** [comment]
Thankyou!
